spring.application.name=Documind_At

server.port=8081

# ✅ Database Configuration (MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/documind_db
spring.datasource.username=root
spring.datasource.password=shanu03

# ✅ JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ✅ Optional (Better Performance)
#spring.jpa.properties.hibernate.format_sql=true

# ✅ File Upload (Important for your project)
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB

# ✅ Logging (Optional)
#logging.level.org.springframework=INFO

# OpenAI main API key (works for all models: chat, embedding, speech, etc.)
spring.ai.openai.api-key=openaikey
